### ISSUE TITLE
It's a rip off

### ISSUE THREAD

**Issue by TTPfrizzy** [MoonmanGod/ToontownPlanet#2]
Hello, i am a staff member from Toontown Planet and i am a fucking homo. God Moonman i want to fuck you so hard now with my pro server that's gonna 420 blaze TTR, please marry me and give me to Golf Wang.

**Comment by MoonmanGod** [comment]
Nigger babies I don't give a fuck, so take it up the butt. One of your current staff leaked this to me, and I see what's going on in the chat still. Toontown Planet is now owned by Golf Wang- heil maverick

**Comment by Loudrob** [comment]
yes that was a lot of ***hard work***
